config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'about', to: 'home#about'
  resources :articles

  get 'signup', to: 'users#new'
  resources 'users', except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources 'categories', except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, uniqueness: true, length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = self.email.downcase }
  has_many :articles
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username, presence: true, uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false },
    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:message] = 'You have to login to perform this action'
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def destroy
    @article.destroy
    flash[:message] = 'Article is deleted successfully!'
    redirect_to articles_path
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:message] = 'Article is created successfully!'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:message] = 'Article is updated successfully!'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def edit
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:error] = 'You can only modify your articles'
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:show, :index]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:message] = 'Category created!'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(
      page: params[:page], per_page: 5
    )
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || !current_user.admin?
      flash[:error] = 'Only admin can do this'
      redirect_to categories_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:message] = "Welcome back, #{user.username}!"
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash.now[:error] = 'Incorrect login information'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:message] = 'You have logged out!'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:message] = 'Thank you for signing up!'
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def update
    if @user.update(user_params)
      flash[:message] = 'Your account has been updated!'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:error] = 'You can only modify your profile'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gavatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag url, alt: user.username + "'s avatar", class: 'rounded-circle'
  end

  def bootstrap_paginate(items)
    will_paginate items, renderer: WillPaginate::ActionView::BootstrapLinkRenderer
  end
end

app/views/articles/_article_list.html.erb
<table class="table table-border">
  <tr>
    <th>Title</th>
    <th>Creator</th>
    <th>Last updated</th>
    <th>Categories</th>
    <th colspan="2">Action</th>
  </tr>
  <% articles.each do |article| %>
    <tr>
      <td><%= link_to article.title, article_path(article) %></td>
      <td><%= link_to(article.user.username, user_path(article.user)) if
      article.user %></td>
      <td><%= time_ago_in_words(article.updated_at) %></td>
      <td><%= render article.categories %></td>
      <% if logged_in? &&
           (current_user === article.user || current_user.admin?) %>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article),
          method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% else %>
        <td></td>
        <td></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/articles/_form.html.erb
<%= render 'shared/model_error', obj: @article %>
<%= form_for @article, html: { class: 'form-group' } do |f| %>
  <p>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  </p>
  <p>
  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>
  </p>
  <p>
  <%= f.label :categories %>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <div class="custom-control custom-checkbox custom-control-inline">
      <%= cb.check_box(class: 'custom-control-input') %>
      <%= cb.label(class: 'custom-control-label') { cb.text } %>
    </div>
  <% end %>
  </p>
  <p>
  <%= f.submit @article.new_record? ? 'Create' : 'Update',
    class: 'btn btn-primary btn-success' %>
</p>
<% end %>

<%= link_to 'Show all articles', articles_path %>

app/views/articles/edit.html.erb
<div class="container">
  <h1 class="mt-5">Edit article</h1>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1 class="mt-5">All articles</h1>

  <div class="text-right mb-5">
    <%= link_to 'New article', new_article_path, class: 'btn btn-primary' %>
  </div>

  <%= render 'article_list', articles: @articles %>
  <%= bootstrap_paginate @articles %>

</div>

app/views/articles/new.html.erb
<div class="container">
  <h1 class="mt-5">New Article</h1>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <h1 class="mt-5"><%=@article.title%><br/></h1>

  <div class="well">
    <small>
      <%= link_to(@article.user.username, user_path(@article.user)) if
      @article.user %>,
      <%= time_ago_in_words(@article.updated_at) %>
    </small>
  </div>

  <hr />

  <article class="mb-5">
    <%=@article.description%><br/>
  </article>

  <% if @article.categories.any? %>
    <div class="mb-5">
      Categories: <%= render @article.categories %>
    </div>
  <% end %>

  <% if logged_in? && (current_user === @article.user || current_user.admin?) %>
    <div class="mb-2">
      <%= link_to 'Edit', edit_article_path(@article),
        class: 'btn btn-sm btn-primary' %>
      <%= link_to 'Delete', article_path(@article),
        method: :delete, data: { confirm: 'Are you sure?' },
        class: 'btn btn-sm btn-danger' %>
    </div>
  <% end %>

  <%= link_to 'Show all articles', articles_path %>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-primary">
  <%= link_to category.name, category_path(category), class: 'text-white' %>
</span>

app/views/categories/index.html.erb
<div class="container">
  <h1 class="mt-5">All categories</h1>

  <div class="text-right mb-5">
    <%= link_to 'New category', new_category_path, class: 'btn btn-primary' %>
  </div>

  <table class="table table-border">
    <tr>
      <th>Title</th>
      <th>Articles</th>
      <th>Created</th>
    </tr>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category_path(category) %></td>
        <td><%= pluralize(category.articles.length, 'article') %></td>
        <td><%= time_ago_in_words(category.updated_at) %></td>
      </tr>
    <% end %>
  </table>
  <%= bootstrap_paginate @categories %>

</div>

app/views/categories/new.html.erb
<div class="container">
  <h1 class="mt-5">New Category</h1>
  <%= render 'shared/model_error', obj: @category %>
  <%= form_for @category, html: { class: 'form-group' } do |f| %>
    <p>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
    </p>
    <p>
    <%= f.submit 'Create', class: 'btn btn-primary btn-success' %>
    </p>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <h1 class="mt-5 text-center"><%= @category.name %></h1>
  <div class="text-center">
    <%= pluralize(@category.articles.length, 'article') %>
  </div>
  <h1 class="mt-5">Articles</h1>
  <%= render 'articles/article_list', articles: @category_articles %>
  <%= bootstrap_paginate @category_articles %>
</div>

app/views/home/about.html.erb
<div class="container">
  <h1>About</h1>
  <%= link_to 'Home', root_path %>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to Alpha Blog</h1>
    <p>Why need ReactJS to make Admin UI?</p>
    <%= link_to 'Sign up', signup_path, class: 'btn btn-primary btn-lg' %>
  </div>
</div>

app/views/layouts/_message.html.erb
<% if !flash[:message].nil? %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= flash[:message] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if !flash[:error].nil? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= flash[:error] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Alpha Blog', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Articles', articles_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Users', users_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a
          class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'All categories', categories_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <% Category.all.each do |category| %>
            <%= link_to category.name, category_path(category),
              class: 'dropdown-item' %>
          <% end %>
          <% if logged_in? && current_user.admin? %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Create new category', new_category_path,
              class: 'dropdown-item' %>
          <% end %>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <% if logged_in? %>
        Welcome <%= 'Admin' if current_user.admin? %>, <%= link_to current_user.username, user_path(current_user) %>
        <%= link_to 'Logout', logout_path, class: 'nav-link', method: 'delete' %>
      <% else %>
        <%= link_to 'Login', login_path, class: 'nav-link' %>
        <%= link_to 'Sign up', signup_path, class: 'nav-link' %>
      <% end %>
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AlphaBlog</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/message' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_model_error.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% obj.errors.full_messages.each do |msg| %>
        <li><%=msg%></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/model_error', obj: @user %>

<div class="row justify-content-md-center">
  <%= form_for @user, html: { class: 'form-group col col-6' } do |f| %>
    <p>
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control' %>
    </p>
    <p>
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
    </p>
    <p>
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
    </p>
    <p>
    <%= f.submit(@user.new_record? ? 'Sign up' : 'Update account',
                 class: 'btn btn-primary btn-success') %>
  </p>
<% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h1 class="mt-5 text-center">Edit account information</h1>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1 class="mt-5">All users</h1>

  <table class="table table-border">
    <tr>
      <th></th>
      <th>Username</th>
      <th>Articles</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= gavatar_for user, size: 20 %></td>
        <td><%= link_to(user.username, user_path(user)) %></td>
        <td><%= pluralize(user.articles.length, 'article') %></td>
      </tr>
    <% end %>
  </table>
  <%= bootstrap_paginate @articles %>

</div>

app/views/users/new.html.erb
<div class="container">
  <h1 class="mt-5 text-center">Sign up</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class="mt-5 text-center"><%= @user.username %>'s page</h1>
  <div class="text-center">
    <%= gavatar_for(@user, size: 150) %>
  </div>
  <% if logged_in? && (current_user === @user || current_user.admin?) %>
    <p align="center" class="mt-3">
    <%= link_to 'Edit profile', edit_user_path(@user) %>
    </p>
  <% end %>
  <h1 class="mt-5">Articles</h1>

  <%= render 'articles/article_list', articles: @user_articles %>
  <%= bootstrap_paginate @user_articles %>
</div>